"""add reservation details fields

Revision ID: 29e476f8b31b
Revises: 0cbb616520ad
Create Date: 2026-01-17 20:34:39.410039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e476f8b31b'
down_revision = '0cbb616520ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=50), nullable=False, server_default='PENDIENTE'))
        batch_op.add_column(sa.Column('teacher_name', sa.String(length=120), nullable=False, server_default='PENDIENTE'))
        batch_op.add_column(sa.Column('subject', sa.String(length=120), nullable=False, server_default='PENDIENTE'))
        batch_op.add_column(sa.Column('signed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('exit_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('teacher_comments', sa.Text(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('teacher_comments')
        batch_op.drop_column('exit_time')
        batch_op.drop_column('signed')
        batch_op.drop_column('subject')
        batch_op.drop_column('teacher_name')
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
