"""widen material text fields

Revision ID: e5b6bda1878f
Revises: b3a7debe1e96
Create Date: 2026-01-15 23:42:50.219230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b6bda1878f'
down_revision = 'b3a7debe1e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('pieces_text',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('serial',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('image_ref',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('tutorial_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('source_file',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('source_sheet',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('source_sheet',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('source_file',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('tutorial_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('image_ref',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('serial',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('model',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('brand',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('pieces_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
